# Generated by Django 6.0.4 on 2026-05-07 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_remove_device_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalledSoftware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
            options={
                'verbose_name': 'Logiciel installé',
                'verbose_name_plural': 'Logiciels installés',
                'ordering': ['name'],
                'unique_together': {('device', 'name')},
            },
        ),
    ]
