# Generated by Django 5.2.13 on 2026-04-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_last_user_alter_device_device_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_user',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
