# Generated by Django 5.2.13 on 2026-04-23 07:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_last_user_alter_device_device_type_and_more'),
        ('rapport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='avg_cpu',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='report',
            name='avg_latency',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='report',
            name='avg_ram',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='report',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='devices.device'),
        ),
        migrations.AlterField(
            model_name='report',
            name='uptime_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
