# Generated by Django 5.2.13 on 2026-04-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('first_connection', 'Premiere connexion'), ('reconnection', 'Reconnexion'), ('disconnection', 'Deconnexion')], max_length=50),
        ),
    ]
