# Generated by Django 6.0.4 on 2026-05-14 07:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField(verbose_name='Commande shell')),
                ('timeout', models.PositiveIntegerField(default=30, verbose_name='Timeout (s)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('success', 'Succès'), ('error', 'Erreur'), ('timeout', 'Timeout'), ('exception', 'Exception')], default='pending', max_length=16)),
                ('stdout', models.TextField(blank=True, default='')),
                ('stderr', models.TextField(blank=True, default='')),
                ('returncode', models.IntegerField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_commands', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='devices.device', verbose_name='Agent cible (vide = broadcast)')),
            ],
            options={
                'verbose_name': 'Commande distante',
                'verbose_name_plural': 'Commandes distantes',
                'ordering': ['-created_at'],
            },
        ),
    ]
